# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class Achievement(BaseModel):
    achievement_type: typing.Optional[types.AchievementType] = Field(default=None, description='Type of achievement. Infer from context.')
    achievement_title: typing.Optional[str] = Field(default=None, description='Title of the achievement as written on the resume.')
    issuing_organization: typing.Optional[str] = Field(default=None, description='Organization that granted the achievement. Null if not mentioned.')
    achievement_date: typing.Optional[str] = Field(default=None, description='Date of the achievement in YYYY-MM format. Null if not mentioned.')
    description: typing.Optional[str] = Field(default=None, description='Description or details of the achievement. Null if not provided.')
    publication_url: typing.Optional[str] = Field(default=None, description='URL of the publication. Null if not a publication or URL not provided.')
    competition_name: typing.Optional[str] = Field(default=None, description='Name of the competition if this is a competition achievement. Null otherwise.')
    position_rank: typing.Optional[str] = Field(default=None, description='Rank or position: \'1st\', \'2nd\', \'finalist\', \'winner\'. Null if not mentioned.')
    award_level: typing.Optional[types.AwardLevel] = Field(default=None, description='Level of the award: international, national, university, department. Null if not determinable.')

class Certification(BaseModel):
    certification_name: typing.Optional[str] = Field(default=None, description='Full name of the certification or course as written on the resume.')
    issuing_organization: typing.Optional[str] = Field(default=None, description='Organization that issued the certification. E.g. \'Microsoft\', \'AWS\', \'Coursera\', \'Google\', \'IBM\', \'Udemy\', \'Coursera\'. Infer from the cert name if clearly implied (e.g., \'AWS Auto ML\' → \'AWS\', \'GCP Specialization\' → \'Google\', \'(IBM)\' in name → \'IBM\'). Null only if truly unidentifiable.')
    certification_type: typing.Optional[types.CertificationType] = Field(default=None, description='Type: certification, course, exam, or accreditation. Infer from context.')
    credential_url: typing.Optional[str] = Field(default=None, description='URL for credential verification if mentioned. Null if not present.')
    issue_date: typing.Optional[str] = Field(default=None, description='Date the certification was issued in YYYY-MM format. Null if not mentioned.')
    expiry_date: typing.Optional[str] = Field(default=None, description='Expiry date in YYYY-MM format. Null if not mentioned or if it doesn\'t expire.')
    score: typing.Optional[str] = Field(default=None, description='Score, grade, or pass/fail result. Null if not mentioned.')
    skill_domain: typing.Optional[str] = Field(default=None, description='Technical domain the certification covers: Data Engineering, Cloud, SQL, BI, AI, etc.')
    level: typing.Optional[types.CertificationLevel] = Field(default=None, description='Difficulty level of the certification. Infer from name/context if obvious, otherwise null.')
    description: typing.Optional[str] = Field(default=None, description='Additional details about the certification. Null if not provided.')

class Education(BaseModel):
    institute_name: typing.Optional[str] = Field(default=None, description='Full name of the educational institution as written on the resume.')
    degree: typing.Optional[str] = Field(default=None, description='Full degree name, e.g. \'Bachelor of Science in Computer Science\', \'MS Computer Science\'.')
    cgpa: typing.Optional[float] = Field(default=None, description='GPA or CGPA as a decimal number (e.g. 3.50). Null if not mentioned.')
    is_currently_attending: typing.Optional[bool] = Field(default=None, description='True if the candidate is still enrolled. Look for \'Expected\', \'Present\', \'Ongoing\'.')
    from_date: typing.Optional[str] = Field(default=None, description='Enrollment start date in YYYY-MM format. Null if not mentioned.')
    end_date: typing.Optional[str] = Field(default=None, description='Graduation/completion date in YYYY-MM format. Null if still attending and no expected date.')
    city: typing.Optional[str] = Field(default=None, description='City of the institution. ONLY extract if the city is LITERALLY written in the resume text — either after a comma in the institute name (e.g., \'University of Punjab, Lahore\' → \'Lahore\') or explicitly stated nearby. Do NOT use your knowledge of where universities are located. If the city is not written in the text, set null.')
    country: typing.Optional[str] = Field(default=None, description='Country of the institution. ONLY extract if explicitly written in the resume text. Do NOT infer from the university name or your knowledge of institution locations. Null if not stated.')
    institution_type: typing.Optional[types.InstitutionType] = Field(default=None, description='Type of institution. Infer from name if obvious (e.g. \'University of X\' → university).')
    field_of_study: typing.Optional[str] = Field(default=None, description='Major or field of study. E.g. \'Computer Science\', \'Data Science\'. Null if only degree name is given without a field.')

class Language(BaseModel):
    language_name: typing.Optional[str] = Field(default=None, description='Name of the language, e.g. \'English\', \'Urdu\', \'Arabic\'.')
    proficiency_level: typing.Optional[types.LanguageProficiency] = Field(default=None, description='Proficiency level. Use the candidate\'s own description if provided, otherwise null.')
    certification_name: typing.Optional[str] = Field(default=None, description='Related certification name like \'IELTS\', \'TOEFL\'. Null if not mentioned.')
    certification_score: typing.Optional[str] = Field(default=None, description='Certification score like \'7.5\', \'C1\'. Null if no certification mentioned.')

class Project(BaseModel):
    project_name: typing.Optional[str] = Field(default=None, description='Name/title of the project as written on the resume.')
    associated_with: typing.Optional[str] = Field(default=None, description='What this project is associated with: company name, university name, \'Personal\', \'Internship\', \'FYP\'. Null if unclear.')
    project_type: typing.Optional[types.ProjectType] = Field(default=None, description='Type of the project. Infer from context (university → academic, company → professional, self → personal).')
    project_description: typing.Optional[str] = Field(default=None, description='ALL description lines and bullet points listed under this project. Include EVERY bullet point from the first to the last, joining them with spaces. Do NOT truncate or summarize — copy every line. Null only if there is genuinely no description text.')
    project_url: typing.Optional[str] = Field(default=None, description='Live project URL if mentioned. Null if not present.')
    repository_url: typing.Optional[str] = Field(default=None, description='GitHub/GitLab repository URL if mentioned. Null if not present.')
    role_in_project: typing.Optional[str] = Field(default=None, description='Candidate\'s role in the project (e.g. \'Team Lead\', \'Developer\'). Null if not mentioned.')
    start_date: typing.Optional[str] = Field(default=None, description='Project start date in YYYY-MM format. Null if not mentioned.')
    end_date: typing.Optional[str] = Field(default=None, description='Project end date in YYYY-MM format. Null if not mentioned.')
    domain: typing.Optional[str] = Field(default=None, description='Technical domain: AI, Web, Data Science, Mobile, Systems, etc. Infer from description if clear.')

class Resume(BaseModel):
    first_name: typing.Optional[str] = Field(default=None, description='Candidate\'s first name. Null only if truly unidentifiable.')
    last_name: typing.Optional[str] = Field(default=None, description='Candidate\'s last name. Null only if truly unidentifiable.')
    salutation: typing.Optional[str] = Field(default=None, description='Title/salutation: Mr., Ms., Dr., etc. Null if not present on the resume.')
    gender: typing.Optional[str] = Field(default=None, description='Gender if explicitly mentioned, inferable from salutation, or strongly implied by a clearly gender-specific first name (e.g., Muhammad/Usama/Ali/Omar/Hassan/Ahmed → \'Male\'; Fatima/Ayesha/Hira/Sara/Maryam → \'Female\'). Use \'Male\' or \'Female\'. Null only if ambiguous.')
    email: typing.Optional[str] = Field(default=None, description='Email address. Extract exactly as written. Null if not present.')
    phone: typing.Optional[str] = Field(default=None, description='Phone number including country code if present. Extract exactly as written. Null if not present.')
    alternate_phone: typing.Optional[str] = Field(default=None, description='Secondary phone number if present. Null if not present.')
    linkedin: typing.Optional[str] = Field(default=None, description='LinkedIn profile URL. Null if not present.')
    github: typing.Optional[str] = Field(default=None, description='GitHub profile URL. Null if not present.')
    nationality: typing.Optional[str] = Field(default=None, description='Nationality if mentioned. Null if not present.')
    city: typing.Optional[str] = Field(default=None, description='Current city of residence. MUST extract from the address block — city is typically the last named location in the address (e.g., \'House no 1794, Police Line, Abbottabad\' → \'Abbottabad\'). Never leave null if an address block is present.')
    country: typing.Optional[str] = Field(default=None, description='Current country of residence. Infer from: (a) explicit mention, (b) known city (Abbottabad/Lahore/Karachi/Islamabad → Pakistan; Dubai/Abu Dhabi → UAE), (c) phone country code (+92 → Pakistan, +971 → UAE, +966 → Saudi Arabia, +44 → UK, +1 → USA/Canada, +91 → India). Null only if no evidence exists.')
    current_address: typing.Optional[str] = Field(default=None, description='Full current address if mentioned. Null if not present.')
    current_role: typing.Optional[str] = Field(default=None, description='Current job title or professional headline from the resume summary/header. Null if not present.')
    qualification: typing.Optional[str] = Field(default=None, description='Highest qualification, e.g., \'BS Computer Science\', \'MBA\'. Infer from education section if present.')
    associated_industry: typing.Optional[str] = Field(default=None, description='Primary industry the candidate works in. MUST infer from job titles with high confidence. E.g., Data Analyst/Data Engineer/BI Analyst → \'Information Technology\'; Software Engineer/Developer → \'Software Development\'; ML/AI Engineer → \'Artificial Intelligence\'; Finance/Accountant → \'Finance\'; Healthcare → \'Healthcare\'. Do NOT leave null when job titles clearly indicate the industry.')
    education: typing.List["Education"] = Field(description='All education entries found on the resume. Empty array if no education section.')
    experience: typing.List["WorkExperience"] = Field(description='All work experience entries. Empty array if no experience section. List in chronological order (newest first).')
    projects: typing.List["Project"] = Field(description='All projects mentioned. Empty array if no projects section.')
    skills: typing.List["Skill"] = Field(description='All skills identified. Extract from skills section AND from experience/project descriptions. Empty array if none found.')
    certifications: typing.List["Certification"] = Field(description='All certifications, courses, and exams. Empty array if none found.')
    languages: typing.List["Language"] = Field(description='Languages the candidate speaks. Empty array if no language section.')
    achievements: typing.List["Achievement"] = Field(description='Awards, honors, publications, scholarships, competition results. Empty array if none found.')

class Skill(BaseModel):
    skill_name: typing.Optional[str] = Field(default=None, description='Name of the skill exactly as recognized. E.g. \'Python\', \'SQL\', \'Machine Learning\', \'Docker\'.')
    skill_category: typing.Optional[types.SkillCategory] = Field(default=None, description='Category of the skill. Classify based on the skill name.')
    proficiency_level: typing.Optional[types.ProficiencyLevel] = Field(default=None, description='Proficiency level. Only set if explicitly stated on the resume, otherwise null. Do NOT guess proficiency.')
    years_of_experience: typing.Optional[float] = Field(default=None, description='Years of experience with this skill. Only set if explicitly mentioned, otherwise null.')
    is_primary: typing.Optional[bool] = Field(default=None, description='True if this is a core skill. Set is_primary=true for: skills in the candidate\'s job title, skills used across multiple roles, skills listed first/prominently in the skills section, or skills mentioned in the profile/summary. Aim to mark 3-6 skills as primary per resume. Set false only for peripheral skills.')

class WorkExperience(BaseModel):
    company_name: typing.Optional[str] = Field(default=None, description='Exact company name as written on the resume. Do NOT guess or fabricate.')
    job_title: typing.Optional[str] = Field(default=None, description='Exact job title/role as written on the resume.')
    from_date: typing.Optional[str] = Field(default=None, description='Start date in YYYY-MM format. Use best effort from resume text. Null if not mentioned.')
    end_date: typing.Optional[str] = Field(default=None, description='End date in YYYY-MM format. Null if this is the current position or not mentioned.')
    is_current_employer: typing.Optional[bool] = Field(default=None, description='True if this is the candidate\'s current/present position. Look for keywords like \'Present\', \'Current\', \'Ongoing\'.')
    country: typing.Optional[str] = Field(default=None, description='Country where the job is located. Null if not mentioned.')
    city: typing.Optional[str] = Field(default=None, description='City where the job is located. Null if not mentioned.')
    employment_type: typing.Optional[types.EmploymentType] = Field(default=None, description='Type of employment. Default to full-time for all standard professional/corporate roles. Use internship if title contains \'intern\'/\'trainee\'; contract if \'contractor\'/\'freelance\'/\'consultant\'; part-time if \'part-time\'. Do NOT leave null for regular professional positions.')
    industry: typing.Optional[str] = Field(default=None, description='Industry sector of the company. Null if not determinable from resume text.')
    job_description: typing.Optional[str] = Field(default=None, description='ALL responsibilities and achievements listed under this position. Include EVERY bullet point and line from the first to the last, joining them with spaces. The description ends only when the next company name, job title, or major section header appears. Do NOT stop after the first few bullets — a 6-bullet role must have all 6 bullets in the output. Null only if there is genuinely no description text.')
    workspace_type: typing.Optional[types.WorkspaceType] = Field(default=None, description='Remote, OnSite, or Hybrid. Only set if explicitly mentioned in resume.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
