# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Achievement": types.Achievement,
    "stream_types.Achievement": stream_types.Achievement,

    "types.Certification": types.Certification,
    "stream_types.Certification": stream_types.Certification,

    "types.Education": types.Education,
    "stream_types.Education": stream_types.Education,

    "types.Language": types.Language,
    "stream_types.Language": stream_types.Language,

    "types.Project": types.Project,
    "stream_types.Project": stream_types.Project,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.Skill": types.Skill,
    "stream_types.Skill": stream_types.Skill,

    "types.WorkExperience": types.WorkExperience,
    "stream_types.WorkExperience": stream_types.WorkExperience,


    "types.AchievementType": types.AchievementType,

    "types.AwardLevel": types.AwardLevel,

    "types.CertificationLevel": types.CertificationLevel,

    "types.CertificationType": types.CertificationType,

    "types.EmploymentType": types.EmploymentType,

    "types.InstitutionType": types.InstitutionType,

    "types.LanguageProficiency": types.LanguageProficiency,

    "types.ProficiencyLevel": types.ProficiencyLevel,

    "types.ProjectType": types.ProjectType,

    "types.SkillCategory": types.SkillCategory,

    "types.WorkspaceType": types.WorkspaceType,

}